title: Awshesh Srivastav
email: awshesh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Father, Tennis Player and a/an Analytics/Data Scientist/AI Specialist showcasing my key projects over last 12+ years of analytics journey changing 
  my designation from Analysts to Analytics Manager to Data Scientist through chaging tides and turns 
  and now i know it hardly matters

show_downloads : True
theme: jekyll-theme-minimal


# Additional configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
