title: Awshesh Srivastav
email: awshesh@gmail.com
show_downloads : True
theme: jekyll-theme-minimal


# Additional configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
